# Generated by Django 3.0.4 on 2020-05-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_id', models.IntegerField()),
                ('dataset', models.CharField(choices=[('flower', 'flower'), ('bird', 'bird'), ('fashion', 'fashion')], max_length=10)),
                ('original', models.FileField(upload_to='<django.db.models.fields.CharField>/<django.db.models.fields.IntegerField>/original.jpg')),
                ('desc', models.TextField()),
                ('result', models.FileField(upload_to='<django.db.models.fields.CharField>/<django.db.models.fields.IntegerField>/result.jpg')),
            ],
        ),
    ]
