# Generated by Django 3.0.4 on 2020-05-01 16:54

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edit',
            name='original',
            field=models.ImageField(upload_to=app.models.orig_file_directory_path),
        ),
        migrations.AlterField(
            model_name='edit',
            name='result',
            field=models.ImageField(upload_to=app.models.result_file_directory_path),
        ),
    ]
